import type { SearchCandidate } from "@/domain/search/types";
import { MEDIA } from "@/config/visual-media";

export type DemoBusiness = {
  id: string;
  name: string;
  slug: string;
  description: string;
  avgRating: number;
  reviewCount: number;
  completeness: number;
  isClaimed: boolean;
  priceLevel: number;
  suburb: string;
  city: string;
  lat: number;
  lng: number;
  categories: string[];
  attributes: string[];
  products: string[];
  services: string[];
  openNow: boolean;
  imageUrl: string | null;
  popularityScore: number;
  freshnessScore: number;
};

/** Development catalog for Pune — used when Supabase is not configured. */
export const PUNE_DEMO_BUSINESSES: DemoBusiness[] = [
  {
    id: "11111111-1111-1111-1111-111111111101",
    name: "Spice Route Kitchen",
    slug: "spice-route-kitchen",
    description: "North Indian classics and rich gravies in Koregaon Park.",
    avgRating: 4.7,
    reviewCount: 214,
    completeness: 92,
    isClaimed: true,
    priceLevel: 2,
    suburb: "Koregaon Park",
    city: "Pune",
    lat: 18.5362,
    lng: 73.8937,
    categories: ["restaurants"],
    attributes: ["north_indian", "vegetarian"],
    products: ["chicken curry", "butter chicken", "garlic naan", "biryani"],
    services: [],
    openNow: true,
    imageUrl: MEDIA.curry,
    popularityScore: 0.86,
    freshnessScore: 0.8,
  },
  {
    id: "11111111-1111-1111-1111-111111111102",
    name: "Curry Leaf Co.",
    slug: "curry-leaf-co",
    description: "Homestyle curries and thalis near FC Road.",
    avgRating: 4.5,
    reviewCount: 98,
    completeness: 84,
    isClaimed: true,
    priceLevel: 1,
    suburb: "FC Road",
    city: "Pune",
    lat: 18.5285,
    lng: 73.8412,
    categories: ["restaurants"],
    attributes: ["north_indian", "vegetarian"],
    products: ["chicken curry", "dal makhani", "paneer tikka"],
    services: [],
    openNow: true,
    imageUrl: MEDIA.thali,
    popularityScore: 0.7,
    freshnessScore: 0.75,
  },
  {
    id: "11111111-1111-1111-1111-111111111103",
    name: "Wok & Bowl",
    slug: "wok-and-bowl",
    description: "Indo-Chinese favourites open late in Baner.",
    avgRating: 4.4,
    reviewCount: 167,
    completeness: 88,
    isClaimed: true,
    priceLevel: 2,
    suburb: "Baner",
    city: "Pune",
    lat: 18.559,
    lng: 73.7868,
    categories: ["restaurants"],
    attributes: ["chinese"],
    products: ["hakka noodles", "chicken manchurian", "schezwan fried rice"],
    services: [],
    openNow: true,
    imageUrl: MEDIA.noodles,
    popularityScore: 0.78,
    freshnessScore: 0.7,
  },
  {
    id: "11111111-1111-1111-1111-111111111104",
    name: "Vesuvio Pizza",
    slug: "vesuvio-pizza",
    description: "Wood-fired pizza and pasta in Viman Nagar.",
    avgRating: 4.6,
    reviewCount: 301,
    completeness: 90,
    isClaimed: true,
    priceLevel: 2,
    suburb: "Viman Nagar",
    city: "Pune",
    lat: 18.5679,
    lng: 73.9143,
    categories: ["restaurants"],
    attributes: ["italian"],
    products: ["margherita pizza", "pepperoni pizza", "garlic pizza"],
    services: [],
    openNow: false,
    imageUrl: MEDIA.pizza,
    popularityScore: 0.9,
    freshnessScore: 0.65,
  },
  {
    id: "11111111-1111-1111-1111-111111111105",
    name: "Green Bowl Kitchen",
    slug: "green-bowl-kitchen",
    description: "Pure-veg bowls and light plates in Aundh.",
    avgRating: 4.8,
    reviewCount: 142,
    completeness: 86,
    isClaimed: true,
    priceLevel: 2,
    suburb: "Aundh",
    city: "Pune",
    lat: 18.558,
    lng: 73.807,
    categories: ["restaurants"],
    attributes: ["vegetarian", "vegan"],
    products: ["buddha bowl", "veggie curry", "falafel wrap"],
    services: [],
    openNow: true,
    imageUrl: MEDIA.vegBowl,
    popularityScore: 0.74,
    freshnessScore: 0.85,
  },
  {
    id: "11111111-1111-1111-1111-111111111106",
    name: "Deccan Roasters",
    slug: "deccan-roasters",
    description: "Specialty coffee and filter coffee near Deccan Gymkhana.",
    avgRating: 4.6,
    reviewCount: 256,
    completeness: 91,
    isClaimed: true,
    priceLevel: 2,
    suburb: "Deccan",
    city: "Pune",
    lat: 18.5167,
    lng: 73.8412,
    categories: ["cafes"],
    attributes: ["south_indian"],
    products: ["flat white", "filter coffee", "cold brew", "croissant"],
    services: [],
    openNow: true,
    imageUrl: MEDIA.coffee,
    popularityScore: 0.88,
    freshnessScore: 0.9,
  },
  {
    id: "11111111-1111-1111-1111-111111111107",
    name: "Fade Room Barbers",
    slug: "fade-room-barbers",
    description: "Precision fades and classic cuts in Kothrud.",
    avgRating: 4.9,
    reviewCount: 188,
    completeness: 95,
    isClaimed: true,
    priceLevel: 2,
    suburb: "Kothrud",
    city: "Pune",
    lat: 18.5074,
    lng: 73.8077,
    categories: ["barbers"],
    attributes: [],
    products: [],
    services: ["fade", "skin fade", "beard trim", "hot towel shave"],
    openNow: true,
    imageUrl: MEDIA.barberCut,
    popularityScore: 0.82,
    freshnessScore: 0.8,
  },
  {
    id: "11111111-1111-1111-1111-111111111108",
    name: "FlowFix Plumbing",
    slug: "flowfix-plumbing",
    description: "Emergency plumbers across central Pune.",
    avgRating: 4.7,
    reviewCount: 76,
    completeness: 80,
    isClaimed: true,
    priceLevel: 3,
    suburb: "Shivajinagar",
    city: "Pune",
    lat: 18.5304,
    lng: 73.8478,
    categories: ["plumbers"],
    attributes: [],
    products: [],
    services: ["leaking tap", "blocked drain", "geyser repair"],
    openNow: true,
    imageUrl: MEDIA.plumberWork,
    popularityScore: 0.6,
    freshnessScore: 0.7,
  },
  {
    id: "11111111-1111-1111-1111-111111111109",
    name: "Misal House",
    slug: "misal-house",
    description: "Spicy Kolhapuri-style misal and everyday Maharashtrian bites.",
    avgRating: 4.3,
    reviewCount: 412,
    completeness: 78,
    isClaimed: true,
    priceLevel: 1,
    suburb: "Camp",
    city: "Pune",
    lat: 18.512,
    lng: 73.879,
    categories: ["restaurants"],
    attributes: ["maharashtrian", "vegetarian"],
    products: ["misal pav", "vada pav", "pohe", "cutting chai"],
    services: [],
    openNow: true,
    imageUrl: MEDIA.thali,
    popularityScore: 0.92,
    freshnessScore: 0.7,
  },
  {
    id: "11111111-1111-1111-1111-111111111110",
    name: "Hinjewadi Biryani Hub",
    slug: "hinjewadi-biryani-hub",
    description: "Dum biryani bowls for the IT crowd.",
    avgRating: 4.4,
    reviewCount: 189,
    completeness: 82,
    isClaimed: true,
    priceLevel: 2,
    suburb: "Hinjewadi",
    city: "Pune",
    lat: 18.5912,
    lng: 73.7389,
    categories: ["restaurants"],
    attributes: ["biryani", "north_indian"],
    products: ["chicken biryani", "mutton biryani", "veg biryani"],
    services: [],
    openNow: true,
    imageUrl: MEDIA.biryani,
    popularityScore: 0.8,
    freshnessScore: 0.75,
  },
];

/** @deprecated Prefer PUNE_DEMO_BUSINESSES */
export const AUCKLAND_DEMO_BUSINESSES = PUNE_DEMO_BUSINESSES;

export function demoToCandidate(
  b: DemoBusiness,
  extras: Partial<SearchCandidate> & {
    distanceM: number | null;
    ftsRank: number;
    trgmSim: number;
    itemMatchScore: number;
    relevance: number;
    matchedVia: string;
    matchedItemName?: string | null;
  },
): SearchCandidate {
  return {
    businessId: b.id,
    name: b.name,
    slug: b.slug,
    avgRating: b.avgRating,
    reviewCount: b.reviewCount,
    completeness: b.completeness,
    isClaimed: b.isClaimed,
    distanceM: extras.distanceM,
    ftsRank: extras.ftsRank,
    trgmSim: extras.trgmSim,
    itemMatchScore: extras.itemMatchScore,
    relevance: extras.relevance,
    matchedVia: extras.matchedVia,
    matchedItemName: extras.matchedItemName ?? null,
    priceLevel: b.priceLevel,
    suburb: b.suburb,
    city: b.city,
    openNow: b.openNow,
    popularityScore: b.popularityScore,
    freshnessScore: b.freshnessScore,
    categories: b.categories,
    imageUrl: b.imageUrl,
    description: b.description,
  };
}
